### ISSUE TITLE
Refactor `TRegx\SafeRegex\preg::match` to `\pattern_match()`

### ISSUE THREAD

**Issue by danon** [t-regx/T-Regx#107]
Currently, documentation states that "you only need to replace `preg_` with `preg::`", but that's not true, since you also need to add the namespace.

We should remove the namesapce so the legacy projects really can be updated without any other change.

Perhaps this change can be only in `t-regx/preg`, not in `t-regx/pattern`.

**Comment by Danon** [comment]
Maybe actually we can rename the methods to `preg2_match`, `preg2_replace()`, `preg2_match_all()`.

**Comment by Danon** [comment]
Or maybe even better, Maybe we could name it `treg_match`, `treg_match_all`, `treg_replace` or `treg_replace_callback`.

**Comment by Danon** [comment]
Should `preg2_match()` restore support for ancient PHP versions, like 5.6 and 5.3?
