### ISSUE TITLE
Prepared patterns could work with dynamic quantifiers

### ISSUE THREAD

**Issue by danon** [t-regx/T-Regx#145]
Usecase for such code

```php
$start = 1;
$end = 4;
\preg_match("/\d{$start,$end}/", $subject);
```
- could be
  ```php
  Pattern::template('\d@')->quantifier(1,3);
  ```
  but that would change the meaning of `@`. Now it means "a value", after the change it could mean "either value or quantifier"
  it would give us validation for improper qunatifiers, but would require another method or an optional argument for unlimited ending-clause. It's unclear how would it behave with `@?` for example.
- or it could be
  ```php
  Pattern::template('(value){1,@}')->integer(3);
  ```
  that's perfhaps the best one, but such notation can be mistakely used with `->literal()` and would potentially break the regexp.
- or it could be
   ```php
  Pattern::template('(value)&')->integer(3);
  ```
  which would introduce new character `&` specifically for quantifiers, but that would make the template more complex, and would require proper control of user mixing the two.
- or it could just inject literal, and throw exception if it's not numeric 
  ```php
  Pattern::template('(value){1,@}')->literal('3');
  ```
  but that relies on base-10 :/

**Comment by Danon** [comment]
We probably should introduce another builder method `->integer(int)`, and placeholders `@` used in absolute quantifiers `{}` can only be bound with `->integer()`.
