### ISSUE TITLE
Replace class do not have `all()` method

### ISSUE THREAD

**Issue by vdauchy** [t-regx/T-Regx#162]
Hello,

Not sure if this a documentation or else issue...
from the documention [limiting-replacements](https://t-regx.com/docs/replace#limiting-replacements) we shall be able to do

 ```
pattern('\d+')->replace($subject)->only(2)->with("___");
pattern('\d+')->replace($subject)->all()->with("___");
```

But looking at the class `TRegx\CleanRegex\Replace\Replace` the methods `all` and `only` do not not exist :-( 

So I'm not sure about how to do a replace all in my case... could you bring some light on this ? Is this the doc not up to date?

Have a good day!

**Comment by Danon** [comment]
Hi, @vdauchy! Thanks for posting the issue!

This is certainly a documentation issue.

```php
$pattern = pattern('\d+');

$pattern->replace($subject)->with("___"); // replace all
$pattern->replace($subject)->limit(2)->with("___"); // replace with limit 2
```

**Comment by vdauchy** [comment]
Hi, thanks for your quick answer ! Indeed it works as you said :-)
Thanks for all the time spent on this package !

**Comment by Danon** [comment]
@vdauchy As I promised, I've written an updated documentation for replacing: https://t-regx.com/docs/replace

Let me know if you need anything else.
