### ISSUE TITLE
Use git tags to release versions

### ISSUE THREAD

**Issue by j3j5** [T-Regx/T-Regx#41]
Hi, I just found out about this library, it looks really good, but I have a question. Is there a reason why you aren't locking releases with git tags?

**Comment by Danon** [comment]
Hey @j3j5 , thanks for writing! :)

I have a few more features to develop before version `1.0.0`, and simultaneously I develop the documentation at [http://t-regx.com](http://t-regx.com).

But of course you're right, I guess i could use tags `0.7`, `0.11`, etc :) In fact, I'm gonna start using them now :)

**Comment by j3j5** [comment]
Awesome!! If I may, would you consider using [semver](https://semver.org/)? It is common practice and makes other people lives easier :)

Anyway, great work, you save my life yesterday on a battle to death I had against `PREG_OFFSET_CAPTURE` and multibyte strings. My head was about to explode till I tried you lib.

Thanks for the good work!

**Comment by Danon** [comment]
Didn't plan it, but I'll definitely use semver, it seams like consistency is a big thing in T-Regx :)

I'm very glad you liked it :D I'm proud to announce you're T-Regx's first user, hooray!

**Comment by j3j5** [comment]
I just saw the alpha release, I think we can close this issue!!

Congrats!!

**Comment by Danon** [comment]
Oh my God, did you really keep an eye for my release? Thank you very much :)
