### ISSUE TITLE
Utilize PHP 7.4.3 flags for replacing

### ISSUE THREAD

**Issue by Danon** [T-Regx/T-Regx#60]
PHP 7.4.3 adds `PREG_OFFSET_CAPTURE` and `PREG_UNMATCHED_AS_NULL` flags.
As reported by:
 - https://github.com/php/php-src/commit/12bcdd68b421a9da50f7f56ea361003997819675
 - https://www.php.net/ChangeLog-7.php (under PHP 7.4)
 - https://bugs.php.net/bug.php?id=77094

We should add another implementation of `Match` interface, that will be used in PHP 7.4+ environments, that use those flags.

**Comment by JakeHarperr** [comment]
Why is this "blocked"?

**Comment by Danon** [comment]
Hello Jake, thanks for contacting! :)

Well, because the PHP ChangeLog, and the release notes promise that `preg_replace_callback()` accepts flags since PHP 7.4, but this test:

```php
$result = [];
preg_replace_callback('/a(b)?c/', 
     function ($match) use (&$result) { $result = $match; },
     'ac', 
     PREG_UNMATCHED_AS_NULL);

var_dump($result);
```
Run online: https://3v4l.org/AKKpZ
proves that it doesn't. So we'll wait for the PHP guys to implement it.

**Comment by Danon** [comment]
Please keep in mind that it would only be an internal implementation. From the use perspective, T-Regx handles all the edge cases correctly under the hood :)
