### ISSUE TITLE
Automatic delimiter that can't cause a conflict

### ISSUE THREAD

**Issue by schlessera** [T-Regx/T-Regx#71]
**Feature description**

I love the fact you have automatic delimiters in the library. However, I think you can improve on the predefined selection of delimiters that throws an exception when all of them are taken.

In WP-CLI, I experimented with using `chr( 1 )` as the delimiter: https://github.com/wp-cli/search-replace-command/blob/master/src/Search_Replace_Command.php#L182

The `chr( 1 )` is the ACII character with the byte value `0x01` and is the "Start of heading" (`SOH`) character.

According to Wikipedia:
> The start of heading (SOH) character was to mark a non-data section of a data stream—the part of a stream containing addresses and other housekeeping data. The start of text character (STX) marked the end of the header, and the start of the textual part of a stream. The end of text character (ETX) marked the end of the data of a message. A widely used convention is to make the two characters preceding ETX a checksum or CRC for error-detection purposes. The end of transmission block character (ETB) was used to indicate the end of a block of data, where data was divided into such blocks for transmission purposes.

As far as I can tell, most of these transmission control characters are not in use anymore, and using `chr( 1 )` should be safe.

This has now been working in production for WP-CLI for two years or more, and there was never an issue with it.

So I want to suggest using `chr( 1 )` as the automatic delimiter, as you will not have the problem of a conflict with the actual pattern.

**Comment by Danon** [comment]
Hey, thanks a lot for leaving a suggestion! :)

I actually was thinking about improving the delimiters myself for a while now, the only idea I had when there was a conflict was to just backslash the usage of the least frequent conflicts. 

But your idea is so much better! I will just have to add an utf-8 check, if someone uses Unicode char with `01` code point but forgets `u` flag, but that's on me :)

Thank you so much again! Great idea, i love it.

**Comment by Danon** [comment]
Nice! I've implemented the change.

Now @schlessera, given how you already worked with those, do you think `chr(1)` should be the first delimiter to try (which will be 99.9999% of cases), and only try the remaining ones if `chr(1)` is present in the pattern?

Or should we go on with `/`, `#`, `%`, `~`, and so on, and only use `chr(1)` when all of those are exhausted?
