### ISSUE TITLE
Support braces as delimiters

### ISSUE THREAD

**Issue by Taluu** [T-Regx/T-Regx#72]
**Feature description**
On the php manual and some place here and there (e.g monolog, symfony sometimes), you can use brackets for delimiters (e.g `{my pattern}` and so on with `()`, `<>`, `[]`) : https://www.php.net/manual/en/regexp.reference.delimiters.php

So when using T-Regx with such delimiter used, it would be great to support the detection of such used patterns.

**Describe what problem does this feature solve**
`Pattern::of('{my pattern [a-zA-Z]+}')` should be correctly interpreted.

**Comment by Danon** [comment]
You can use any delimiter compatible with PCRE, if you're using `Pattern::pcre()` (instead of `Pattern::of()` :)

```php
Pattern::pcre('{my pattern [a-zA-Z]+}')->test('my pattern Taluu');
```

To use `Pattern::of()`, try skipping the delimiters:

```php
Pattern::off('my pattern [a-zA-Z]+')->test('my pattern Taluu');
```

If you have any other questions, please don't hesitate!

**Comment by Taluu** [comment]
Oh great, I just had a quick look around and saw that the `Delimiters` class didn't support it as they are "special" kind of delimiter. But if we can use them with `pcre`, then all the better. :}

**Comment by Danon** [comment]
@Taluu Yea, there's even a dedicated test for that :)
https://github.com/T-Regx/T-Regx/blob/master/test/Unit/TRegx/CleanRegex/Internal/Delimiter/DelimitererTest.php

`Pattern::of()` is for safe automatic delimiters, `Pattern::pcre()` is for people who use their own delimiters.

Glad I could help! :) If you have other questions, please do continue :) Closing the issue now.

PS: FYI Seeing how you asked this question, you might be interested in T-Regx's smart alternative for `preg_quote()` - please take a look at: https://t-regx.com/docs/handling-user-input first - you can also use `of`/`pcre` with them.
