### ISSUE TITLE
Remove Pattern::prepare()

### ISSUE THREAD

**Issue by Danon** [T-Regx/T-Regx#78]
Multiple arrays make for messy design, unintuitive design, unexpected unsafe string usage. With `inject()`, `bind()` it's impossible to misuse the parameter. Alterntion is array, in array in array. Nightmare. Please, remove.

**Comment by ibarrajo** [comment]
![image](https://user-images.githubusercontent.com/1480657/93972820-a8c99300-fd38-11ea-9424-9d5ba3326bae.png)

perhaps we can keep breaking changes in major version updates..

**Comment by Danon** [comment]
@ibarrajo Hello, thank you for leaving the delightful meme.

I'm terribly sorry you've experienced inconenvience because of the breaking change I introduced. We'll try to minimize breaking changes in the future, you can be sure of that.

As to the issue at hand, I understand you've been using it? Then you'll be happy to hear that we've decided to bring `Pattern::prepare()` back, with small limitation.

**Comment by Danon** [comment]
The restored `Pattern::prepare()` will be brought back in `0.10.0`. 

```php
Pattern::prepare(["^foo:", [$value], "$"]); // this will be allowed
```
but this won't:
```php
Pattern::prepare(["^foo:", [$eitherOne, $orTheOther], "$"]); // \InvalidArgumentException
```

**Comment by ibarrajo** [comment]
Thank you @Danon for following up on this!

**Comment by Danon** [comment]
@ibarrajo The restored version is on `develop` branch. You can reference `dev-develop` in your `composer.json` or wait until day after tommorow when I release `0.10.0`.
