### ISSUE TITLE
Add API for constructing flags

### ISSUE THREAD

**Issue by Danon** [T-Regx/T-Regx#94]
Ideas:

```php
Flags::enableUnicode()           // prefixed with "enable"
  ->enableMultiline()            // prefixed with "enable"
  ->disableCaseInsensitive();    // prefixed with "disabled"
```
or

```php
Flags::unicode()
  ->multiline()                  // unprefixed
  ->noCaseInsensitive();         // prefixed with "no"
```
or
```php
Flags::setUnicode(true)
  ->setMultiline(true)           // toggle with boolean arg
  ->setCaseInsensitive(false);
```

**Comment by danilopinotti** [comment]
Hello!
First, I really appreciate your work.

Recently I used a MQTT library that uses the third approach: https://github.com/php-mqtt/client#connection-settings
I think it is more flexible, once we can set the property in a variable, and don't need any additional "ifs", example:
```php
Flags::setUnicode(true)
    ->setCaseInsensitive($this->hasUpperCaseCharacters($string));
```

Other way:
```php
$flags = Flags::setUnicode(true);

if ($this->hasUpperCaseCharacters($string)) {
    $flags->setCaseInsensitive();
}
```

**Comment by Danon** [comment]
@danilopinotti Thanks for reaching out!

That's actually a valid point, honestly I didn't think of conditional flags, I first thought they would be constant at compiletime, but of course you're right. 

So obviously, because of conditional flags we need "toggle-style" flags. I have two additional questions now, that I'll have to answer.

Approach 4th
```php
class Flags {
  public function unicode(bool $unicode = true);
  public function multiline(bool $unicode = true);
}

// [...]

Flags::unicode()              // enable "unicode"
  ->anchoring(true)           // enable "anchoring"
  ->caseInsensitive(false);   // disable "case insensitive"
  ->multiline()               // enable "multiline"
```
